export const dummy_response = {
    "from_lang": "en",
    "movies": [
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "Romance",
            "id": 438212,
            "keywords": "anime-short film taking pictures forest photographer",
            "original_language": "zh",
            "overview": "While taking pictures in a remote forest a young photographer encounters a beautiful mysterious girl. The photographer soon discovers that the girl has been missing and is being held captive in the forest.",
            "popularity": 0.6,
            "poster_path": "/jLphVjWAInqwWmyCl57LOde2Dnq.jpg",
            "production_companies": "Sun's Motion Picture Co.",
            "recommendations": "nan",
            "release_date": "Thu, 25 Oct 1979 00:00:00 GMT",
            "revenue": 0,
            "runtime": 93,
            "title": "By Love Obsessed",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "/2yvkggwPSiko5sTPqWBiA7RcZdj.jpg",
            "budget": 0,
            "genres": "Animation-Family-Fantasy",
            "id": 410379,
            "keywords": "anime-short film",
            "original_language": "fr",
            "overview": "In a forest in the mountains a little girl makes a mysterious encounter.",
            "popularity": 0.655,
            "poster_path": "/A3SWozUyrkB6cgRjOm4tEbUc0FL.jpg",
            "production_companies": "Gobelins",
            "recommendations": "nan",
            "release_date": "Mon, 08 Sep 2014 00:00:00 GMT",
            "revenue": 0,
            "runtime": 3,
            "title": "Nebula",
            "vote_average": 7.0,
            "vote_count": 2
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "Action",
            "id": 474188,
            "keywords": "",
            "original_language": "en",
            "overview": "The Girl In The Woods is a short film which explores crime honor and violence in a post truth hyper real world. It follows two social outcasts Beatrix and Charlie who find solace in one another while facing quirky characters they meet on the way from brothel girls to art dealers. In the quest to save the orphanage where they not only met but had the only sense of home they find the money to pay off the orphanages debt by stealing from a Snuff director Mr Sunshine. Triggering a showdown between between bad and not as bad. This short combines crime comedy and a splash of blood.",
            "popularity": 0.6,
            "poster_path": "/15ql4HnIqGeRuF6tlMAnjBSKs6B.jpg",
            "production_companies": "",
            "recommendations": "nan",
            "release_date": "Mon, 04 Sep 2017 00:00:00 GMT",
            "revenue": 0,
            "runtime": 18,
            "title": "The Girl in the Woods",
            "vote_average": 10.0,
            "vote_count": 1
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "Animation-Fantasy",
            "id": 817608,
            "keywords": "",
            "original_language": "en",
            "overview": "An exploration of the relationship between a young girl and the forest spirit she awakens.",
            "popularity": 0.6,
            "poster_path": "/tqFIUyj6SsErqPAHQ3b2475VAPX.jpg",
            "production_companies": "University of South Wales",
            "recommendations": "nan",
            "release_date": "Sun, 10 May 2015 00:00:00 GMT",
            "revenue": 0,
            "runtime": 5,
            "title": "Evanescent",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "",
            "id": 755139,
            "keywords": "",
            "original_language": "en",
            "overview": "Mila is a girl who is in the forest. As she enters she stumbles across a hole containing three masks and a note that says: Your decision who will it be? Take a mask and put it on.",
            "popularity": 0.6,
            "poster_path": "/mff4ULYLrk1kRkx5MtLwWlJiG6Q.jpg",
            "production_companies": "",
            "recommendations": "nan",
            "release_date": null,
            "revenue": 0,
            "runtime": 4,
            "title": "Mask Out",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "",
            "id": 633542,
            "keywords": "sh f",
            "original_language": "pt",
            "overview": "In a forest clearing as she runs away from an invisible menace a little girl meets a strange-looking child.",
            "popularity": 0.6,
            "poster_path": "/rQHyAITQRsINh3s7LCKrMuKMydF.jpg",
            "production_companies": "",
            "recommendations": "nan",
            "release_date": "Fri, 04 Oct 2019 00:00:00 GMT",
            "revenue": 0,
            "runtime": 6,
            "title": "A Little Taste",
            "vote_average": 5.8,
            "vote_count": 3
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "",
            "id": 718809,
            "keywords": "",
            "original_language": "pt",
            "overview": "A girl sleeps in the woods and wakes up for life.",
            "popularity": 0.6,
            "poster_path": "/7vMSTvuPutGg5kScJJO6aCey0zh.jpg",
            "production_companies": "Filmes do Asilo Febril",
            "recommendations": "nan",
            "release_date": "Fri, 26 Jun 2020 00:00:00 GMT",
            "revenue": 0,
            "runtime": 26,
            "title": "Spell in the Park",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "",
            "id": 420213,
            "keywords": "",
            "original_language": "pt",
            "overview": "A young girl disappears in a forest in the heart of S\u00e3o Paulo Brazil.",
            "popularity": 0.6,
            "poster_path": "/pJWXef6p8KSYx0R7Nb2wwQhotmD.jpg",
            "production_companies": "",
            "recommendations": "nan",
            "release_date": "Thu, 20 Oct 2016 00:00:00 GMT",
            "revenue": 0,
            "runtime": 33,
            "title": "Mata Atl\u00e2ntica",
            "vote_average": 5.0,
            "vote_count": 1
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "Horror",
            "id": 767139,
            "keywords": "",
            "original_language": "tl",
            "overview": "A girl takes a stroll through the woods when she is pursued by an unidentified entity. Later she discovers that the entity is a visitor she has been expecting all along.",
            "popularity": 0.6,
            "poster_path": "/oPp6P3AMfSI7bUVltACQFK6O0eI.jpg",
            "production_companies": "",
            "recommendations": "nan",
            "release_date": "Sat, 28 Oct 2017 00:00:00 GMT",
            "revenue": 0,
            "runtime": 4,
            "title": "The Arrival",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "Thriller-Action-Horror",
            "id": 466165,
            "keywords": "",
            "original_language": "en",
            "overview": "A young girl runs for her life in a haunted forest and finds that sometimes your fears are real.",
            "popularity": 1.349,
            "poster_path": "/8axXVqA1RGoLS5Nx9gzagaySBsH.jpg",
            "production_companies": "",
            "recommendations": "",
            "release_date": "Tue, 06 Jun 2017 00:00:00 GMT",
            "revenue": 0,
            "runtime": 9,
            "title": "Dead Run",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "",
            "id": 856414,
            "keywords": "",
            "original_language": "en",
            "overview": "A teen girl gets lost in a deep forest she appears to be in danger and frantically tries to find a way out.  A monologizing voice-over enters that of a woman who evokes her loneliness.",
            "popularity": 0.6,
            "poster_path": "/29yNzMRcaZR4yB1vbUQhQ13M7qa.jpg",
            "production_companies": "",
            "recommendations": "nan",
            "release_date": null,
            "revenue": 0,
            "runtime": 35,
            "title": "Shadow",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "Horror",
            "id": 832602,
            "keywords": "short film",
            "original_language": "en",
            "overview": "In the dark woods a girl in a cage awaits the return of the man with the knife.",
            "popularity": 1.345,
            "poster_path": "",
            "production_companies": "",
            "recommendations": "",
            "release_date": "Fri, 10 Oct 2014 00:00:00 GMT",
            "revenue": 0,
            "runtime": 8,
            "title": "Girl",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "",
            "budget": 50,
            "genres": "Adventure",
            "id": 931774,
            "keywords": "waltzofqualm",
            "original_language": "en",
            "overview": "A teenage girl found a broken mirror in the forest and discovered the one thing she had been escaping from.",
            "popularity": 0.6,
            "poster_path": "/zYOvRG2OtLaKUABNOzamDO1pTt2.jpg",
            "production_companies": "SineSibol",
            "recommendations": "nan",
            "release_date": "Sat, 27 Feb 2021 00:00:00 GMT",
            "revenue": 98,
            "runtime": 9,
            "title": "Waltz of Qualm",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "",
            "budget": 11000,
            "genres": "Adventure-Fantasy",
            "id": 686184,
            "keywords": "",
            "original_language": "en",
            "overview": "A troubled girl follows a magical being into the woods where her fears take on fantastic forms.",
            "popularity": 0.6,
            "poster_path": "/onOzo9XyZSNu104HC6VvuSeXiIV.jpg",
            "production_companies": "Horromance Productions",
            "recommendations": "nan",
            "release_date": "Fri, 14 Sep 2018 00:00:00 GMT",
            "revenue": 0,
            "runtime": 19,
            "title": "Sylphvania Grove",
            "vote_average": 10.0,
            "vote_count": 1
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "",
            "id": 917692,
            "keywords": "",
            "original_language": "en",
            "overview": "A young girl's life is changed forever when she meets a stranger in a quiet woodland clearing.",
            "popularity": 0.6,
            "poster_path": "/oD0ck23VrQOpx5u84TNL1T04Rrs.jpg",
            "production_companies": "",
            "recommendations": "nan",
            "release_date": null,
            "revenue": 0,
            "runtime": 9,
            "title": "Finding Wilson",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "",
            "id": 633257,
            "keywords": "",
            "original_language": "en",
            "overview": "A queer fairy tale in which an eerie yet charming forest spirit leads a girl into the woods.",
            "popularity": 1.353,
            "poster_path": "/e3nsjWtEeJ3NvYugJeOS0htFLBi.jpg",
            "production_companies": "",
            "recommendations": "",
            "release_date": "Wed, 31 Oct 2018 00:00:00 GMT",
            "revenue": 0,
            "runtime": 6,
            "title": "The Flickering Forest",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "/5Tp5TLCv6Aqu7xvfnFM9Emv1DWf.jpg",
            "budget": 0,
            "genres": "Thriller-Horror",
            "id": 257567,
            "keywords": "japan-loss of loved one-forest-revenge-grieving parents",
            "original_language": "ja",
            "overview": "Mayu the teen girl hasn\u2019t opened her heart to anyone since ten years ago when some terrible case happened. Instead of going to high school she goes to the church every day and looks for redemption. One day she disappears in the woods silently and suddenly. On the other side Mana lives with her husband and her seven-year-old daughter in happiness. However an unexpected occurrence happens and tears their happiness apart. Her little girl Sakura plays in the woods and goes missing. Mana loses her mind because of sadness. What is there inside the woods?",
            "popularity": 1.126,
            "poster_path": "/29Wt6DOMzl94JSpEOnEwx4QXeAY.jpg",
            "production_companies": "Stardust Pictures",
            "recommendations": "nan",
            "release_date": "Sat, 20 Aug 2011 00:00:00 GMT",
            "revenue": 0,
            "runtime": 84,
            "title": "Vanished: Age 7",
            "vote_average": 7.5,
            "vote_count": 5
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "Drama-Animation",
            "id": 362143,
            "keywords": "philippines",
            "original_language": "en",
            "overview": "The beginning was when a young girl wanders off to the forest she suddenly meets a bunch of forest spirits that seemingly only she can see for when her mother found her she's dancing all by herself. Nevertheless even as she grew she never forgot them and she visited them despite the very forest was starting to get swallowed up by urbanization.",
            "popularity": 0.6,
            "poster_path": "",
            "production_companies": "National Commission for Culture and the Arts",
            "recommendations": "nan",
            "release_date": "Thu, 01 Jan 2009 00:00:00 GMT",
            "revenue": 0,
            "runtime": 15,
            "title": "Mutya",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "Animation",
            "id": 878283,
            "keywords": "",
            "original_language": "en",
            "overview": "A young girl is lost in the woods looking for her mum; however she stumbles upon a different kind of mother.",
            "popularity": 0.6,
            "poster_path": "/9xU8qlwMpt0SMte2GfKJcyuIzRS.jpg",
            "production_companies": "",
            "recommendations": "nan",
            "release_date": "Thu, 22 Apr 2021 00:00:00 GMT",
            "revenue": 0,
            "runtime": 2,
            "title": "Mama Nature",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "",
            "id": 796335,
            "keywords": "",
            "original_language": "en",
            "overview": "A lonely girl meets a lonely boy in the woods.",
            "popularity": 0.6,
            "poster_path": "/o0ZoMJLtbBeOEku1f4tzN5SjGLc.jpg",
            "production_companies": "",
            "recommendations": "nan",
            "release_date": "Sun, 14 Jun 2020 00:00:00 GMT",
            "revenue": 0,
            "runtime": 8,
            "title": "The Girl From No Where",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "",
            "id": 394395,
            "keywords": "",
            "original_language": "en",
            "overview": "A girl walking slowly in the woods",
            "popularity": 0.6,
            "poster_path": "",
            "production_companies": "",
            "recommendations": "nan",
            "release_date": "Sun, 24 Apr 2011 00:00:00 GMT",
            "revenue": 0,
            "runtime": 5,
            "title": "Una muchacha de lento andar",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "",
            "id": 880279,
            "keywords": "",
            "original_language": "en",
            "overview": "A girl wakes up in the middle of an unfamiliar forest with no recollection of why she's there. When she sees light coming from a distant flashlight she follows it hoping to find a way out of the dark but discovers that the person carrying the flashlight is her own image reflected in the mirror.",
            "popularity": 0.6,
            "poster_path": "/69B2KTHV77D7f91vFWL5XJS9ZGP.jpg",
            "production_companies": "",
            "recommendations": "nan",
            "release_date": "Thu, 01 Oct 2020 00:00:00 GMT",
            "revenue": 0,
            "runtime": 11,
            "title": "Once Familiar",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "Horror",
            "id": 766200,
            "keywords": "based on myths legends or folklore-saci",
            "original_language": "pt",
            "overview": "A girl crosses the forest to get milk and on the way she knows about Saci who punishes those who do not respect the people of the forest.",
            "popularity": 0.6,
            "poster_path": "/xoAr05iBv9jqhnwmeCD6a4WDxlX.jpg",
            "production_companies": "F\u00e1bulas Negras Produ\u00e7\u00f5es",
            "recommendations": "nan",
            "release_date": "Sat, 24 Jan 2015 00:00:00 GMT",
            "revenue": 0,
            "runtime": 18,
            "title": "O Saci",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "/jCCVtobjqOoUw4XvZa79QtbxTmD.jpg",
            "budget": 0,
            "genres": "Fantasy",
            "id": 663046,
            "keywords": "",
            "original_language": "it",
            "overview": "A girl walking in the woods is captured by an evil dwarf. He takes her home and forces her to keep house for him. Thanks to a beautiful fairy and the mice she takes care of she escapes.",
            "popularity": 0.6,
            "poster_path": "/xqqxrz162ZCG4Fw8ONEkxpFwKFi.jpg",
            "production_companies": "Societ\u00e0 Anonima Ambrosio",
            "recommendations": "nan",
            "release_date": "Wed, 01 Jan 1908 00:00:00 GMT",
            "revenue": 0,
            "runtime": 7,
            "title": "The Grateful Mice",
            "vote_average": 7.0,
            "vote_count": 1
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "",
            "id": 181726,
            "keywords": "",
            "original_language": "en",
            "overview": "A girl wakes up in the middle of the woods with no memory of what has happened prior to that. She is injured and confused when she starts seeing a shape or figure that is following her.",
            "popularity": 0.6,
            "poster_path": "",
            "production_companies": "",
            "recommendations": "nan",
            "release_date": "Wed, 01 Sep 2010 00:00:00 GMT",
            "revenue": 0,
            "runtime": 27,
            "title": "R\u00e9compence",
            "vote_average": 4.3,
            "vote_count": 3
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "Drama",
            "id": 749483,
            "keywords": "",
            "original_language": "en",
            "overview": "After two days alone in the woods a young girl's reality begins to blend with her favorite comic book.",
            "popularity": 0.6,
            "poster_path": "/9YD03MPbl1ChQDJOsERaTTeaKHz.jpg",
            "production_companies": "",
            "recommendations": "nan",
            "release_date": "Sun, 18 Nov 2018 00:00:00 GMT",
            "revenue": 0,
            "runtime": 17,
            "title": "Frontier",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "",
            "id": 400142,
            "keywords": "woman director",
            "original_language": "en",
            "overview": "After discovering her eldest daughter\u2019s diary a mother decides to take her two daughters into the forest.",
            "popularity": 0.6,
            "poster_path": "",
            "production_companies": "",
            "recommendations": "nan",
            "release_date": "Fri, 07 Aug 2015 00:00:00 GMT",
            "revenue": 0,
            "runtime": 18,
            "title": "The River Under the Tongue",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "Horror-Thriller-Mystery",
            "id": 82655,
            "keywords": "oregon usa-surrealism-gore-vision",
            "original_language": "en",
            "overview": "A girl gets in a car accident and wanders through the woods encountering all kinds of nightmarish things.",
            "popularity": 2.238,
            "poster_path": "/xF6vUtDriP9KSV71gBbkKMTZq4d.jpg",
            "production_companies": "",
            "recommendations": "",
            "release_date": "Mon, 24 Jan 2011 00:00:00 GMT",
            "revenue": 0,
            "runtime": 81,
            "title": "The Oregonian",
            "vote_average": 4.9,
            "vote_count": 19
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "Music",
            "id": 941423,
            "keywords": "",
            "original_language": "fi",
            "overview": "A girl with a golden star in front of her face runs in the forest.",
            "popularity": 0.6,
            "poster_path": "",
            "production_companies": "",
            "recommendations": "nan",
            "release_date": "Thu, 03 Feb 2005 00:00:00 GMT",
            "revenue": 0,
            "runtime": 8,
            "title": "The Two Left Hands of the Surrealist",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "Drama",
            "id": 869923,
            "keywords": "",
            "original_language": "ru",
            "overview": "Young Masha Zvonareva makes her way into the dark thicket of the forest for a magic flower that can fulfill any desire. The girl for the first time realizes what she really wants.",
            "popularity": 0.6,
            "poster_path": "/anPicYKybqew2mANLFdeBLUIsrl.jpg",
            "production_companies": "",
            "recommendations": "nan",
            "release_date": "Mon, 13 Sep 2021 00:00:00 GMT",
            "revenue": 0,
            "runtime": 14,
            "title": "First Line",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "/2MRPIOKs7cFLbuzTGj30SB4O2D7.jpg",
            "budget": 0,
            "genres": "Drama",
            "id": 882689,
            "keywords": "",
            "original_language": "en",
            "overview": "A girl thought to be a witch sleepwalks towards a specific part of the forest. Will she be absolved of this burden and is there more to the story than it meets the eye?",
            "popularity": 0.6,
            "poster_path": "/e1UeSECJ9GvLb5gmVY1RrD3YD9j.jpg",
            "production_companies": "Divine Touch Productions Ltd.",
            "recommendations": "nan",
            "release_date": "Fri, 01 Jun 2018 00:00:00 GMT",
            "revenue": 0,
            "runtime": 147,
            "title": "Adamma My Love",
            "vote_average": 7.0,
            "vote_count": 1
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "Animation",
            "id": 872202,
            "keywords": "",
            "original_language": "uk",
            "overview": "Both a tale and a parable about a girl who one day disappears from her room and appears in a magic forest. And what's most interesting she has a fish tail. In the forest the Girl meets the Iron Wolf who speaks in riddles and tells her a tale. The girl goes through different lands and meets the Death. In all that she is driven by her desire to discover her true dream.",
            "popularity": 0.6,
            "poster_path": "/nw2esgeUaj3czF6EqXfWzkhhDuI.jpg",
            "production_companies": "",
            "recommendations": "nan",
            "release_date": "Thu, 17 Jul 2014 00:00:00 GMT",
            "revenue": 0,
            "runtime": 15,
            "title": "The Fish-Tailed Girl",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "Fantasy-Family",
            "id": 949442,
            "keywords": "",
            "original_language": "pt",
            "overview": "A girl runs away from home to be with her friend a fantastic forest creature while her parents desperately try to find her.",
            "popularity": 0.6,
            "poster_path": "/mNwhwpGubGEebUEOzS70gxxvFou.jpg",
            "production_companies": "Escola das Artes - Universidade Cat\u00f3lica",
            "recommendations": "nan",
            "release_date": "Wed, 27 Feb 2019 00:00:00 GMT",
            "revenue": 0,
            "runtime": 9,
            "title": "Se na floresta um sopro",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "Drama-Mystery-Romance",
            "id": 283542,
            "keywords": "china-tradition-village-forest-tension-conflict-relationship-culture-dialect-sichuanese dialect",
            "original_language": "zh",
            "overview": "Xiaofan a young girl who works at a Karaoke Club awakes one morning in a remote forest with her body covered in blood. As she struggles to find her way out she tries to understand the drama circumstances which got her into the situation events mainly related to her unpredictable boyfriend. She needs to make a decision that may change her life.",
            "popularity": 1.024,
            "poster_path": "/sKYd9Pz9ohATU6vExFAb276cPr7.jpg",
            "production_companies": "Almost Red Productions",
            "recommendations": "283353-283633-283674",
            "release_date": "Sat, 09 Nov 2013 00:00:00 GMT",
            "revenue": 0,
            "runtime": 29,
            "title": "Ni Jing: Thou Shalt Not Steal",
            "vote_average": 8.2,
            "vote_count": 6
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "",
            "id": 475865,
            "keywords": "",
            "original_language": "en",
            "overview": "Walking in the forest Clara a disenchanted girl from the Roman suburbs bumps into a deer. Hoping to catch that magical moment the young girl points her phone camera towards the animal but the phone turns off leaving her only with a doubt and a beautiful memory. This event starts a one-day journey marked by encounters with different characters a path that becomes a search into a corrupted memory.",
            "popularity": 0.6,
            "poster_path": "/hIqy9Qj2BxF9MNhnyCR7JR8Z8uK.jpg",
            "production_companies": "",
            "recommendations": "nan",
            "release_date": "Tue, 03 Oct 2017 00:00:00 GMT",
            "revenue": 0,
            "runtime": 20,
            "title": "Adavede",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "Fantasy-Horror-Music",
            "id": 722571,
            "keywords": "",
            "original_language": "en",
            "overview": "A teenage girl ventures into the woods to solve the disappearance of her beloved younger brother. Haunting discoveries transcend the search beyond time bringing happiness at the cost of her very soul.",
            "popularity": 0.6,
            "poster_path": "/vEk4TA70BtqkIuGmcVGI2Pisant.jpg",
            "production_companies": "",
            "recommendations": "nan",
            "release_date": "Mon, 27 Jan 2014 00:00:00 GMT",
            "revenue": 0,
            "runtime": 60,
            "title": "Beneath Glass Trees",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "/bksaBJcw24IaVVAXsbEWIuY5T1o.jpg",
            "budget": 0,
            "genres": "Horror",
            "id": 869666,
            "keywords": "",
            "original_language": "ru",
            "overview": "A teenage girl runs into unknown creatures beside the abandoned car in the night forest.",
            "popularity": 0.6,
            "poster_path": "/uWdI7Grqfn5PqxTZR7eHn0Gk8Hi.jpg",
            "production_companies": "",
            "recommendations": "nan",
            "release_date": "Fri, 27 Aug 2021 00:00:00 GMT",
            "revenue": 0,
            "runtime": 0,
            "title": "From the Dark",
            "vote_average": 10.0,
            "vote_count": 1
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "",
            "id": 796328,
            "keywords": "",
            "original_language": "en",
            "overview": "A young girl wanders through the woods reminiscing on the time she spent there with her boyfriend before his death.",
            "popularity": 0.6,
            "poster_path": "/mnjsF6FfSnQqdpsL2a5fHAQeUGr.jpg",
            "production_companies": "",
            "recommendations": "nan",
            "release_date": "Thu, 10 Sep 2020 00:00:00 GMT",
            "revenue": 0,
            "runtime": 12,
            "title": "Walk Where He Walked",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "Animation",
            "id": 561529,
            "keywords": "",
            "original_language": "xx",
            "overview": "As the silhouette of a lonely girl runs through the woods something in the shadows is lurking her.",
            "popularity": 0.904,
            "poster_path": "/zRTUkOKMwyjvacRk45iutAiNg0O.jpg",
            "production_companies": "True3D-Valdemar",
            "recommendations": "nan",
            "release_date": "Sat, 17 Mar 2012 00:00:00 GMT",
            "revenue": 0,
            "runtime": 5,
            "title": "Red",
            "vote_average": 6.5,
            "vote_count": 2
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "Horror",
            "id": 824761,
            "keywords": "",
            "original_language": "en",
            "overview": "Inspired by the DarkBox Silent Horror comic strip written by K.S. . A hiker comes across a girl in distress while traveling through the woods but she is not what she appears to be.",
            "popularity": 0.84,
            "poster_path": "/gg997sGbSHs2NSJKtr6fwyfUzuZ.jpg",
            "production_companies": "A Buck Short Productions",
            "recommendations": "nan",
            "release_date": "Wed, 09 Oct 2019 00:00:00 GMT",
            "revenue": 0,
            "runtime": 4,
            "title": "Hiker",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "/yQaraIrhraBRvCgX5q0ZYCSAI1t.jpg",
            "budget": 0,
            "genres": "Animation-Fantasy-Drama",
            "id": 24154,
            "keywords": "anime",
            "original_language": "ja",
            "overview": "After being deserted by her parents 11-year old Miyori shuts her heart from the rest of the world and denies any form of human relationships. She was entrusted in the care of her grandmother who lives near a forest. Miyori will take a walk in the forest where she felt a strong sense of loneliness in the forest which seems to have nothing. However she soon encounters unbelievable things...",
            "popularity": 3.708,
            "poster_path": "/8s19MXQUNyLnWvZ55wcAF0GS2VM.jpg",
            "production_companies": "Kadokawa-Fuji Television Network-Nippon Animation-Kansai Television-BS Fuji",
            "recommendations": "83389",
            "release_date": "Sat, 14 Nov 2009 00:00:00 GMT",
            "revenue": 0,
            "runtime": 107,
            "title": "Miyori's Forest",
            "vote_average": 7.2,
            "vote_count": 25
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "",
            "id": 862648,
            "keywords": "",
            "original_language": "pt",
            "overview": "It's Saturday in the woods: strange noises draw the girl's attention. It's the Devil.",
            "popularity": 0.6,
            "poster_path": "/ds8UNhurNGOUK2SqgTsQMvem22K.jpg",
            "production_companies": "Filmes do Asilo Febril",
            "recommendations": "nan",
            "release_date": "Tue, 09 Nov 2021 00:00:00 GMT",
            "revenue": 0,
            "runtime": 0,
            "title": "S\u00e1bado no mato",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "Horror",
            "id": 731222,
            "keywords": "",
            "original_language": "en",
            "overview": "A little girl being hunted by a masked killer in the wilderness",
            "popularity": 0.909,
            "poster_path": "/NDfQQnMcIlmHIN6nRLrwhhpgUr.jpg",
            "production_companies": "",
            "recommendations": "nan",
            "release_date": "Mon, 13 Jul 2020 00:00:00 GMT",
            "revenue": 0,
            "runtime": 65,
            "title": "I Think We're Alone Now",
            "vote_average": 2.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "Horror-Mystery",
            "id": 745934,
            "keywords": "banshee-short film",
            "original_language": "en",
            "overview": "While she was under the supervision of her big sister Olivia got lost into the woods overnight and got back with something different. She didn't come back alone.",
            "popularity": 0.6,
            "poster_path": "/aint79lVeU89WzsxWAViQk828Qh.jpg",
            "production_companies": "Al\u00e9as Films-Fake Digital Entertainment-Stormdust Pictures",
            "recommendations": "nan",
            "release_date": "Sat, 01 Oct 2016 00:00:00 GMT",
            "revenue": 0,
            "runtime": 14,
            "title": "Banshee",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "Drama",
            "id": 423857,
            "keywords": "woman director-short film",
            "original_language": "fr",
            "overview": "An eight-year-old girl is fascinated by the exquisite corpse of a young woman she finds in the woods.",
            "popularity": 0.624,
            "poster_path": "/bqVrZAW5Suqe4INl0X4SJVmxODn.jpg",
            "production_companies": "GREC",
            "recommendations": "nan",
            "release_date": "Sat, 02 Feb 2013 00:00:00 GMT",
            "revenue": 0,
            "runtime": 25,
            "title": "Exquisite Corpse",
            "vote_average": 4.0,
            "vote_count": 1
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "Animation",
            "id": 711122,
            "keywords": "",
            "original_language": "en",
            "overview": "Ponkina is a little girl.  One morning she leaves her home to take a walk in the forest.  She is met with a surprise hiding in a bush: a cat.",
            "popularity": 0.6,
            "poster_path": "",
            "production_companies": "BL Cartoons",
            "recommendations": "nan",
            "release_date": "Wed, 20 Oct 2010 00:00:00 GMT",
            "revenue": 0,
            "runtime": 4,
            "title": "Ponkina",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "Fantasy-Horror",
            "id": 738141,
            "keywords": "",
            "original_language": "en",
            "overview": "Will you follow Lily into the Forest?",
            "popularity": 0.6,
            "poster_path": "/3Q7olcIbGYV9ryarqnWJEYz7dJn.jpg",
            "production_companies": "La Victoria Productions",
            "recommendations": "nan",
            "release_date": "Sat, 06 Jun 2020 00:00:00 GMT",
            "revenue": 0,
            "runtime": 5,
            "title": "Dandelions",
            "vote_average": 5.0,
            "vote_count": 1
        },
        {
            "backdrop_path": "/9KAncJ3DBXahSZEUVE3XDrSMV6A.jpg",
            "budget": 0,
            "genres": "Horror-Drama-History",
            "id": 736845,
            "keywords": "ambush-mexican revolution-pirate-revoluci\u00f3n mexicana",
            "original_language": "es",
            "overview": "A girl plays at being a pirate when she learns that her father's ranch will be invaded. Convinced that she can help she goes into the forest not knowing that she will find something worse.",
            "popularity": 0.619,
            "poster_path": "/bIQSihaArvnQRezgICYkeOQlrG7.jpg",
            "production_companies": "Centro de Capacitaci\u00f3n Cinematogr\u00e1fica (CCC)",
            "recommendations": "nan",
            "release_date": "Tue, 25 Aug 2020 00:00:00 GMT",
            "revenue": 0,
            "runtime": 15,
            "title": "Captain Blackbeard",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "Horror-Mystery",
            "id": 829613,
            "keywords": "",
            "original_language": "as",
            "overview": "The plot revolves around a kid getting fascinated by a mysterious voice coming from a forest nearby.",
            "popularity": 1.117,
            "poster_path": "/b231MhMTyzsDrDMSlYOkVLbTW5B.jpg",
            "production_companies": "",
            "recommendations": "nan",
            "release_date": "Sat, 12 Sep 2020 00:00:00 GMT",
            "revenue": 0,
            "runtime": 1,
            "title": "Daityo (The Demon)",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "",
            "id": 435769,
            "keywords": "",
            "original_language": "ja",
            "overview": "The repeated sequence of \"a girl appearing in the woods burying dead insects and then leaving\" is made without a camera. With each repetition the film images are broken down and the color is fading. The girl is performed by the filmmaker herself channeling media as a medium. This film is structural but also has a narrative.",
            "popularity": 0.6,
            "poster_path": "",
            "production_companies": "",
            "recommendations": "nan",
            "release_date": "Sun, 18 Jan 2009 00:00:00 GMT",
            "revenue": 0,
            "runtime": 12,
            "title": "A Child Goes Burying Dead Insects",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "Animation",
            "id": 257910,
            "keywords": "",
            "original_language": "en",
            "overview": "Antonia doesn't like her life and daydreams all day long in an imaginary forest which she doesn't want to leave. Her father will take the right steps to bring her girl to her senses but when she comes to them she will shock everybody.",
            "popularity": 0.6,
            "poster_path": "",
            "production_companies": "",
            "recommendations": "nan",
            "release_date": "Sat, 20 Mar 2010 00:00:00 GMT",
            "revenue": 0,
            "runtime": 6,
            "title": "The Forest",
            "vote_average": 6.0,
            "vote_count": 3
        },
        {
            "backdrop_path": "/lMXKRlzeHbHLEgBL4jQVR0NFsCr.jpg",
            "budget": 0,
            "genres": "Horror",
            "id": 46313,
            "keywords": "forest-woods-unrequited love-doctor-supernatural being-japanese horror-hospital setting",
            "original_language": "ja",
            "overview": "A young woman named Kazue runs over a naked girl on a mountain road. When she stops to help the girl runs off into an old abandoned house in the middle of the woods.",
            "popularity": 2.223,
            "poster_path": "/mETsC9iHWcuktNwZzBGcBM1857r.jpg",
            "production_companies": "Arcimboldo Y.K.-Art Port Inc",
            "recommendations": "",
            "release_date": "Sat, 16 Apr 2005 00:00:00 GMT",
            "revenue": 0,
            "runtime": 72,
            "title": "Tomie: Revenge",
            "vote_average": 4.5,
            "vote_count": 14
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "",
            "id": 833346,
            "keywords": "",
            "original_language": "tr",
            "overview": "A young girl plays aguitar in the jungle. She is lonely and unhappy. However the forest animals who heard the music begin to gather beside the girl and listen tothemusic. The little girl is surprised when she seesthat scene. Suddenly a monster emerges among the bushes. The music stops and everyone gets stunned and scared. But the monster smiles everyone relaxes and the music starts again.",
            "popularity": 0.6,
            "poster_path": "",
            "production_companies": "",
            "recommendations": "nan",
            "release_date": null,
            "revenue": 0,
            "runtime": 2,
            "title": "The Power Of Music",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "/oadznRtneEe1axPgoG2mAzgPzVC.jpg",
            "budget": 0,
            "genres": "Drama",
            "id": 683790,
            "keywords": "psychic power-lost child",
            "original_language": "da",
            "overview": "When a little girl goes missing in the woods her parents are at a loss as to what to do. To their great relief a boy with a sixth sense shows the way to the girl using his psychic abilities.",
            "popularity": 1.341,
            "poster_path": "/umjz1Qf2Rn7OQQl3rabDceRW8Sf.jpg",
            "production_companies": "Nordisk Films Kompagni",
            "recommendations": "nan",
            "release_date": "Thu, 26 Sep 1907 00:00:00 GMT",
            "revenue": 0,
            "runtime": 6,
            "title": "The Boy with the Sixth Sense",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "/c4T4ajKmkA1GXg5I8yQLRKMSTQu.jpg",
            "budget": 28000000,
            "genres": "Animation-Family-Fantasy-Romance-Music",
            "id": 28032,
            "keywords": "witch-fairy-widow-musical-mole-miniature people-wanting a baby-based on fairy tale-spinster-forced marriage-talking animals",
            "original_language": "en",
            "overview": "The tiny girl meets a fairy prince who saves her from the creatures of the woods.",
            "popularity": 21.963,
            "poster_path": "/eBvSSfwAKgcjF4eyaeNSzTCpfaF.jpg",
            "production_companies": "Warner Bros. Pictures-Warner Bros. Family Entertainment-Sullivan Bluth Studios",
            "recommendations": "22586-18948-13225-18937-54113-19164-12233-15139-28302-17337-11497-19004-21032-15997-34942-9948-9078-13761-20235-10948-10693",
            "release_date": "Tue, 29 Mar 1994 00:00:00 GMT",
            "revenue": 11373501,
            "runtime": 86,
            "title": "Thumbelina",
            "vote_average": 6.5,
            "vote_count": 430
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "Fantasy-Horror",
            "id": 813244,
            "keywords": "",
            "original_language": "pt",
            "overview": "Ane spends her afternoons playing around the forest with her cousins until she encounters Anhang\u00e1 an indigenous spirit that surrounds her community. But when she goes deeper into the forest Ane is faced with a real haunting.",
            "popularity": 0.6,
            "poster_path": "/phOJiiThUbtLy1ckhwvNUx9R0aj.jpg",
            "production_companies": "Jamary Filmes",
            "recommendations": "nan",
            "release_date": "Fri, 16 Apr 2021 00:00:00 GMT",
            "revenue": 0,
            "runtime": 18,
            "title": "Jamary",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "/jLAlNrq2sTkkWHyN8WOl5FYNo7t.jpg",
            "budget": 0,
            "genres": "Thriller-Drama-Mystery-Science Fiction",
            "id": 500944,
            "keywords": "mushroom-cave-short film-lost girl",
            "original_language": "en",
            "overview": "After finding a mysterious totem in a cave while on a hike with her friend a wayward teenage girl goes missing.",
            "popularity": 0.941,
            "poster_path": "/mf83GkGHBlvxbnFovvP7PbCqfkk.jpg",
            "production_companies": "First Hunt Films",
            "recommendations": "nan",
            "release_date": "Sun, 01 Apr 2018 00:00:00 GMT",
            "revenue": 0,
            "runtime": 14,
            "title": "After Her",
            "vote_average": 5.0,
            "vote_count": 3
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "Animation",
            "id": 869289,
            "keywords": "short film",
            "original_language": "en",
            "overview": "A girl decides to break out of the noisy city and flee to nature in order to escape the social problems of today. What awaits her at the end of the journey?",
            "popularity": 0.6,
            "poster_path": "/2yRrjJA9iLHesUzsUW0UYUsyPMh.jpg",
            "production_companies": "Studio Baku",
            "recommendations": "nan",
            "release_date": null,
            "revenue": 0,
            "runtime": 3,
            "title": "Urban Escape",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "/2GI7lCr46OVdQc7zgLWyTuBejnV.jpg",
            "budget": 0,
            "genres": "Animation",
            "id": 220920,
            "keywords": "stop motion-woman director-short film",
            "original_language": "es",
            "overview": "Sof\u00eda a little girl of seven remembers the day she fractured her arm while being chased through the forest; a story full of fantasy that hides a heart rending moment in Sof\u00eda's life.",
            "popularity": 0.6,
            "poster_path": "/4RAbISn1tQtsWsss7DqVWHwn4A0.jpg",
            "production_companies": "Instituto Mexicano de Cinematograf\u00eda-Consejo Nacional para la cultura y las artes",
            "recommendations": "nan",
            "release_date": "Sat, 03 Mar 2012 00:00:00 GMT",
            "revenue": 0,
            "runtime": 8,
            "title": "Rain in the Eyes",
            "vote_average": 8.5,
            "vote_count": 1
        },
        {
            "backdrop_path": "",
            "budget": 15000,
            "genres": "Family-Fantasy",
            "id": 466799,
            "keywords": "forest-coming of age-short film",
            "original_language": "pt",
            "overview": "Trying to prove her courage little Joana accepts the challenge of entering the woods supposedly haunted by an ancient spirit.",
            "popularity": 0.6,
            "poster_path": "/uuaGX5go7fNOONdpv4LNn3v0O5z.jpg",
            "production_companies": "Filmes da Garoa",
            "recommendations": "nan",
            "release_date": "Thu, 16 Feb 2017 00:00:00 GMT",
            "revenue": 0,
            "runtime": 15,
            "title": "The spirit of the woods",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "/tA6HrULowH7r2fKSvrSNsEVrLq4.jpg",
            "budget": 0,
            "genres": "Horror",
            "id": 740624,
            "keywords": "monster-sister-tormentor-lost in the woods-abandoned building-short film",
            "original_language": "es",
            "overview": "The walk from school of two sisters will be altered when the youngest takes an unexplored path into the woods that leads her to a disquieting abandoned institution. Mesmerized by the building the girl founds a scorch sketch book that warns about a menacing presence surrounding her but her innocence doesn\u2019t let her see that her life is in danger.",
            "popularity": 0.62,
            "poster_path": "/en1UjAyTjw3uESsWpjbN5IIHEHO.jpg",
            "production_companies": "",
            "recommendations": "nan",
            "release_date": "Mon, 07 Sep 2020 00:00:00 GMT",
            "revenue": 0,
            "runtime": 10,
            "title": "Ashes",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "Family-Animation-Adventure-Comedy",
            "id": 456117,
            "keywords": "",
            "original_language": "es",
            "overview": "Micaela loves the nature that surrounds her playing games and going on adventures with her friends. Then one day she learns of an evil plot to change the forest's colors to black and gray.",
            "popularity": 0.6,
            "poster_path": "/g13fnJ4bc0zy2FtqgAXj1dMPJgn.jpg",
            "production_companies": "Laboratorios Stagnaro-Encuadre S.A.",
            "recommendations": "nan",
            "release_date": "Thu, 05 Dec 2002 00:00:00 GMT",
            "revenue": 0,
            "runtime": 90,
            "title": "Micaela, una pel\u00edcula m\u00e1gica",
            "vote_average": 2.0,
            "vote_count": 1
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "Horror-Fantasy-Adventure-Drama",
            "id": 486725,
            "keywords": "",
            "original_language": "en",
            "overview": "Eternity a 10-year-old girl lives in a gatehouse at the edge of an ancient forest and she likes to dig for buried treasure. One day she digs up something she shouldn't and the forest wants it back.",
            "popularity": 2.984,
            "poster_path": "/ineY7xSH64PRStK6nJDCfri0xnU.jpg",
            "production_companies": "Lost Eye Films-Gothic Manor",
            "recommendations": "",
            "release_date": "Sat, 01 Oct 2016 00:00:00 GMT",
            "revenue": 0,
            "runtime": 97,
            "title": "The Gatehouse",
            "vote_average": 6.8,
            "vote_count": 6
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "Drama",
            "id": 468215,
            "keywords": "short film",
            "original_language": "pt",
            "overview": "In a small Brazilian town a teenage girl works everyday in a eucalyptus forest where she chases ants away with pesticides. Yet her inner struggle turns out to be the real fight.",
            "popularity": 0.939,
            "poster_path": "/fqAgNbmxNvU32Xi7Ho2WzSeBOKx.jpg",
            "production_companies": "",
            "recommendations": "nan",
            "release_date": "Tue, 01 Aug 2017 00:00:00 GMT",
            "revenue": 0,
            "runtime": 13,
            "title": "Ant Killers",
            "vote_average": 5.0,
            "vote_count": 3
        },
        {
            "backdrop_path": "/g4qPgIwL3jdADu6VSVecIwBL2TM.jpg",
            "budget": 0,
            "genres": "Horror",
            "id": 525905,
            "keywords": "",
            "original_language": "en",
            "overview": "One morning Jodi wonders into the woods near her house. Her father claims the woods are haunted and has warned her for years to stay out of them. After returning is she still his daughter? Or something else?",
            "popularity": 0.6,
            "poster_path": "/8I0HY7QWMkTr15aLGrhTJyNKQiA.jpg",
            "production_companies": "",
            "recommendations": "nan",
            "release_date": "Sat, 28 Oct 2017 00:00:00 GMT",
            "revenue": 0,
            "runtime": 8,
            "title": "Night Light",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "/6gzWm5rle78AvfEU9G27C8aVhwr.jpg",
            "budget": 0,
            "genres": "Family-Drama",
            "id": 359926,
            "keywords": "undocumented immigrant-lost in the woods",
            "original_language": "es",
            "overview": "Six-year-old Aurora is abandoned in the mountains by human traffickers. She wanders until she finds a cabin in the woods.",
            "popularity": 1.4,
            "poster_path": "/7t2OHBV6zJVMfcAWjzJXFkg5S6I.jpg",
            "production_companies": "Do More Productions",
            "recommendations": "",
            "release_date": "Sat, 11 Apr 2015 00:00:00 GMT",
            "revenue": 0,
            "runtime": 21,
            "title": "Aurora",
            "vote_average": 6.0,
            "vote_count": 2
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "Family-Fantasy",
            "id": 424611,
            "keywords": "woman director",
            "original_language": "en",
            "overview": "In All About A Girl an ordinary game of \"let's pretend\" turns uncanny as alone in the woods a young girl projects life voice and ultimately her own identity onto an unexpected surrogate in a doll's dress.",
            "popularity": 0.6,
            "poster_path": "/9KoHsPWbMS6c8DNEfm3so5tKqhY.jpg",
            "production_companies": "",
            "recommendations": "nan",
            "release_date": "Thu, 01 Jan 2004 00:00:00 GMT",
            "revenue": 0,
            "runtime": 6,
            "title": "All About a Girl",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "",
            "id": 886712,
            "keywords": "",
            "original_language": "sv",
            "overview": "The existential story of the tree girl and her ascension.",
            "popularity": 0.6,
            "poster_path": "",
            "production_companies": "",
            "recommendations": "nan",
            "release_date": "Wed, 30 Sep 2009 00:00:00 GMT",
            "revenue": 0,
            "runtime": 5,
            "title": "Tr\u00e4dflickan",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "/8IuDDi2bNu2at9zU7765gfHBMjE.jpg",
            "budget": 0,
            "genres": "Mystery-Horror-Thriller",
            "id": 6948,
            "keywords": "monster-forest-disappearance",
            "original_language": "en",
            "overview": "Set in 1965 New England a troubled girl encounters mysterious happenings in the woods surrounding an isolated girls school that she was sent to by her estranged parents.",
            "popularity": 11.218,
            "poster_path": "/lQWtLTy7xBxXx1l89sSQRfplHXm.jpg",
            "production_companies": "United Artists-Furst Films-SLS Video Productions-Cinerenta Feature Films-Cinegreen",
            "recommendations": "",
            "release_date": "Mon, 25 Sep 2006 00:00:00 GMT",
            "revenue": 0,
            "runtime": 91,
            "title": "The Woods",
            "vote_average": 5.7,
            "vote_count": 209
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "Animation-Fantasy",
            "id": 740406,
            "keywords": "",
            "original_language": "pt",
            "overview": "A girl plays in the forest of brain trees. A fruit falls into her lap and she takes it home triggering a great family transformation.",
            "popularity": 0.6,
            "poster_path": "",
            "production_companies": "",
            "recommendations": "nan",
            "release_date": "Mon, 07 Sep 2020 00:00:00 GMT",
            "revenue": 0,
            "runtime": 5,
            "title": "Comendo C\u00e9rebros",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "/7Q57CQRxKKAmxPvLzSRLzBJUtRL.jpg",
            "budget": 13000000,
            "genres": "Adventure-Family",
            "id": 5139,
            "keywords": "human animal relationship-fox-season-forest-brown bear-little girl",
            "original_language": "fr",
            "overview": "A young girl of about 10 years lives in a solitary peasant's house on the edge of the jurassic mountains in the East of France. One day in autumn when she is on her way to school through the forest she observes a hunting fox. Of course the fox flees from her but the girl feels a strong desire to meet the fox again.",
            "popularity": 9.672,
            "poster_path": "/eBpc03hS9A7QPv0k6AZfDCdKURt.jpg",
            "production_companies": "Canal+-France 3 Cin\u00e9ma-Bonne Pioche Productions-Path\u00e9-Wild Bunch Distribution-Picturehouse",
            "recommendations": "539819-74944-31203-21788-182219-102207-2454-204668-5528-54318-10140-17350-1667-53457-9317-9986-10488-21861-41211-21348-2284",
            "release_date": "Thu, 27 Dec 2007 00:00:00 GMT",
            "revenue": 29610210,
            "runtime": 94,
            "title": "The Fox and the Child",
            "vote_average": 6.5,
            "vote_count": 316
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "Drama",
            "id": 688385,
            "keywords": "",
            "original_language": "ur",
            "overview": "Oblique eerie and mysterious 'The Girl' is about the violence and horror of childhood. The Girl lives in an isolated mansion in the woods in the mountains of India with a woman the 'Mad Lady.' This woman is her caretaker and watches her all the time. Their odd life is disrupted when the Mad Lady can see something she was previously oblivious to.  Inspired by Indian Gothic greats like 'Mahal' from the forties and the European avant-garde films from the twenties 'The Girl' is a gothic tale about the resilience of children.",
            "popularity": 0.84,
            "poster_path": "",
            "production_companies": "Four Nine and a Half Pictures",
            "recommendations": "nan",
            "release_date": "Sun, 16 Feb 2014 00:00:00 GMT",
            "revenue": 0,
            "runtime": 8,
            "title": "Bachpan: The Girl",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "/yPRnoFEhj09i824pqmE2cwfedsN.jpg",
            "budget": 0,
            "genres": "Fantasy-Adventure-Animation-Family",
            "id": 430447,
            "keywords": "witch-based on novel or book-cat-magic-school of witchcraft-based on children's book-anime",
            "original_language": "ja",
            "overview": "Mary Smith a young girl who lives with her great-aunt in the countryside follows a mysterious cat into the nearby forest where she finds a strange flower and an old broom none of which is as ordinary as it seems.",
            "popularity": 20.413,
            "poster_path": "/lq3OJQiJ8hlCr23LAdHbeU3eqBF.jpg",
            "production_companies": "STUDIO PONOC",
            "recommendations": "978436-51739-475215-38142-242828-79707-431819-378108-16859-15370-15283-472983-110420-476292-579741-12429-513347-198375-610892-631132-83389",
            "release_date": "Sat, 08 Jul 2017 00:00:00 GMT",
            "revenue": 0,
            "runtime": 103,
            "title": "Mary and The Witch's Flower",
            "vote_average": 7.128,
            "vote_count": 658
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "Animation",
            "id": 884846,
            "keywords": "",
            "original_language": "ru",
            "overview": "A girl from a savage tribe once comes to a resolution that she wants more from life than eating quarry and she escapes the cave for the world outside.",
            "popularity": 0.6,
            "poster_path": "",
            "production_companies": "",
            "recommendations": "nan",
            "release_date": "Fri, 30 Oct 2020 00:00:00 GMT",
            "revenue": 0,
            "runtime": 5,
            "title": "Follow Me",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "/en1XAePgWqNSXb82luUMmo5u3cF.jpg",
            "budget": 5000000,
            "genres": "Fantasy-Horror-Mystery",
            "id": 542224,
            "keywords": "witch-fairy tale-woods-tale-witchcraft-dark fantasy-based on fairy tale-folk horror-re-imagining-brother sister relationship-supernatural power",
            "original_language": "en",
            "overview": "A long time ago in a distant fairy tale countryside a young girl leads her little brother into a dark wood in desperate search of food and work only to stumble upon a nexus of terrifying evil.",
            "popularity": 23.005,
            "poster_path": "/mBBBXseq4k4dI63k06XIrsc02j8.jpg",
            "production_companies": "Automatik Entertainment-Bron Studios-Creative Wealth Media Finance-Orion Pictures-Wild Atlantic Pictures",
            "recommendations": "492611-465086-539537-555974-570670-443791-474764-605804-567609-514847-539181-639798-582913-545609-495764-571384-458305-511987-521029-483202-501170",
            "release_date": "Thu, 30 Jan 2020 00:00:00 GMT",
            "revenue": 22304357,
            "runtime": 87,
            "title": "Gretel & Hansel",
            "vote_average": 5.99,
            "vote_count": 1218
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "Horror-Thriller",
            "id": 625121,
            "keywords": "",
            "original_language": "en",
            "overview": "12-year-old Trisha McFarland strays from the path while she and her recently divorced mother and brother take a hike along a branch of the Appalachian Trail. Lost for days wandering farther and farther astray Trisha has only her portable radio for comfort. A huge fan of Tom Gordon a Boston Red Sox relief pitcher she listens to baseball games and fantasizes that her hero will save her. Nature isn\u2019t her only adversary though \u2013 something dangerous may be tracking Trisha through the dark woods.",
            "popularity": 0.6,
            "poster_path": "",
            "production_companies": "Village Roadshow Pictures-Vertigo Entertainment-Stampede Ventures-Origin Story",
            "recommendations": "nan",
            "release_date": null,
            "revenue": 0,
            "runtime": 0,
            "title": "The Girl Who Loved Tom Gordon",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "",
            "id": 771256,
            "keywords": "",
            "original_language": "de",
            "overview": "A young girl roams through the wild nature with binoculars walkie-talkie and a big pinch of joy of discovery. She is fascinated by found objects such as old sneakers and sees the special in all the things around her. She collects her strange booty on a big old tree - on which one day an older man is leaning asleep who actually wanted to find something completely different than Tilda in this place.",
            "popularity": 0.6,
            "poster_path": "",
            "production_companies": "",
            "recommendations": "nan",
            "release_date": null,
            "revenue": 0,
            "runtime": 10,
            "title": "Tildas Trost",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "Adventure",
            "id": 363761,
            "keywords": "amazon rainforest",
            "original_language": "de",
            "overview": "A young girl seeking to unravel the mystery of her father's death travels through the Amazon jungle into a nightmare of danger.",
            "popularity": 1.4,
            "poster_path": "/iTRsgvoxmbMJeRrgkU3yVE8FxgG.jpg",
            "production_companies": "Piran-Film-Atl\u00e2ntida Cinematogr\u00e1fica-UFA",
            "recommendations": "",
            "release_date": "Fri, 06 Dec 1963 00:00:00 GMT",
            "revenue": 0,
            "runtime": 86,
            "title": "River of Evil",
            "vote_average": 6.0,
            "vote_count": 1
        },
        {
            "backdrop_path": "/wEebeCOMh62q52d8qE1W98YpPvx.jpg",
            "budget": 0,
            "genres": "Drama",
            "id": 25054,
            "keywords": "",
            "original_language": "ja",
            "overview": "Three high school girls living out in the country build stories out from their local environment mountainous and bordered by an unkempt buried forest.",
            "popularity": 1.118,
            "poster_path": "/5NkqJFFgXbqHHshdcqPj9r6KaYp.jpg",
            "production_companies": "Himawari Theater Group",
            "recommendations": "nan",
            "release_date": "Thu, 12 May 2005 00:00:00 GMT",
            "revenue": 0,
            "runtime": 93,
            "title": "The Buried Forest",
            "vote_average": 6.3,
            "vote_count": 13
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "Drama",
            "id": 495886,
            "keywords": "",
            "original_language": "en",
            "overview": "About a girl.",
            "popularity": 0.625,
            "poster_path": "/ziJfhV9z7sTmavdQBrCWirAQVM8.jpg",
            "production_companies": "",
            "recommendations": "nan",
            "release_date": "Wed, 01 Oct 2014 00:00:00 GMT",
            "revenue": 0,
            "runtime": 138,
            "title": "Himmatwali",
            "vote_average": 4.0,
            "vote_count": 1
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "",
            "id": 586613,
            "keywords": "",
            "original_language": "en",
            "overview": "A girl gets a glimpse of the future at the bottom of a submerged mountain village.",
            "popularity": 0.6,
            "poster_path": "/mcsGFC4AsdS3pJTbizSqlzU2U1w.jpg",
            "production_companies": "",
            "recommendations": "nan",
            "release_date": null,
            "revenue": 0,
            "runtime": 5,
            "title": "Rising Water",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "",
            "id": 649047,
            "keywords": "",
            "original_language": "en",
            "overview": "A young woman travels to an isolated hilly location to reach an old farmhouse that her distant uncle bequeathed her. During the exploration of the building in a drawer she finds an old photo of a little girl and a letter with the warning about the magical influences of that place. After a restless sleep interested in solving the mistery that scares her she decides to go into the woods that surround the farmhouse pushed by an enigmatic force that leads her to an imposing tree. Between the roots she finds a TV that suddendly turns on showing the same tree in a bygone era. Around the tree two little girls similar to the one in the photo seem to happily play together...",
            "popularity": 0.6,
            "poster_path": "",
            "production_companies": "",
            "recommendations": "nan",
            "release_date": "Tue, 09 Jul 2019 00:00:00 GMT",
            "revenue": 0,
            "runtime": 79,
            "title": "Les nymphes et la nuit",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "Horror",
            "id": 596532,
            "keywords": "short film",
            "original_language": "es",
            "overview": "Susana a teenager girl scout walks with her friends into the woods to play a mysterious rite of initiation.",
            "popularity": 0.6,
            "poster_path": "/bgAnpnXaEVubUN7pFcFaECbFO6v.jpg",
            "production_companies": "",
            "recommendations": "nan",
            "release_date": "Thu, 31 May 2018 00:00:00 GMT",
            "revenue": 0,
            "runtime": 18,
            "title": "The Game Behind The Dark",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "/ti1rdWtvVSX0BCPAxIXn8Satjyg.jpg",
            "budget": 0,
            "genres": "Drama",
            "id": 704197,
            "keywords": "",
            "original_language": "xx",
            "overview": "The girl in a summer day left alone by the lake meets her inner darkness. While drowning in her thoughts she falls in daydream mind tricks itself reality becomes delusional. The animal beautiful spirit comes to save here.",
            "popularity": 0.6,
            "poster_path": "/mpjQRB1lIo5OUEXvgX48PfCxEnk.jpg",
            "production_companies": "",
            "recommendations": "nan",
            "release_date": "Tue, 15 Jan 2013 00:00:00 GMT",
            "revenue": 0,
            "runtime": 4,
            "title": "Darkness",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "Animation-Fantasy",
            "id": 891069,
            "keywords": "monster-short film-kids",
            "original_language": "en",
            "overview": "Gabby keeps bothering her older sister Tam to play so Tam tells a story about a monster that lives in the forest. Whatever you do she says you can\u2019t let it see your face...",
            "popularity": 0.6,
            "poster_path": "/fmN6h85xLdCbaoWEEkiwOIxj3za.jpg",
            "production_companies": "Royal College of Art",
            "recommendations": "nan",
            "release_date": "Fri, 21 Jun 2013 00:00:00 GMT",
            "revenue": 0,
            "runtime": 6,
            "title": "The Thing Under the Tree",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "Animation",
            "id": 448878,
            "keywords": "",
            "original_language": "ru",
            "overview": "The weather was beautiful. Princess was awful. At two o'clock in the afternoon princess get lost in the woods. Or maybe it was the other way around?",
            "popularity": 0.6,
            "poster_path": "/kYd8U37RzOhoSymUkZze5rBMMc.jpg",
            "production_companies": "Soyuzmultfilm",
            "recommendations": "nan",
            "release_date": "Fri, 25 Mar 1977 00:00:00 GMT",
            "revenue": 0,
            "runtime": 5,
            "title": "Princess and Cannibal",
            "vote_average": 8.0,
            "vote_count": 3
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "Drama-Horror",
            "id": 443664,
            "keywords": "",
            "original_language": "en",
            "overview": "When her sister disappears from a camping trip nine year old Fae is left wondering if the scary stories about her new home are true.",
            "popularity": 0.6,
            "poster_path": "",
            "production_companies": "",
            "recommendations": "nan",
            "release_date": "Tue, 16 Aug 2016 00:00:00 GMT",
            "revenue": 0,
            "runtime": 10,
            "title": "The Holes Beneath the Trees",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "/9vV00ECWbQF4sso9STotDfsiDVA.jpg",
            "budget": 0,
            "genres": "Animation",
            "id": 575095,
            "keywords": "short film",
            "original_language": "pl",
            "overview": "After running away from her depressing village in eastern Europe a teenage girl meets a new friend under a bridge.",
            "popularity": 0.915,
            "poster_path": "/rGFPQ8SCyWrLGYmhz0R6nFC9t1d.jpg",
            "production_companies": "Animoon",
            "recommendations": "nan",
            "release_date": "Sun, 27 Jan 2019 00:00:00 GMT",
            "revenue": 0,
            "runtime": 26,
            "title": "Acid Rain",
            "vote_average": 6.1,
            "vote_count": 9
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "",
            "id": 478178,
            "keywords": "",
            "original_language": "pl",
            "overview": "A girl wakes up after a night spent with a man in an elegant room of a palace on the outskirts of the city. The girl gets into her car drives off goes through villages fields into the forest. On the road there is a log blocking her way. The girl pulls the log onto the side of the road. A truck approaches from behind and starts aggressively pursuing her.",
            "popularity": 0.6,
            "poster_path": "",
            "production_companies": "",
            "recommendations": "nan",
            "release_date": "Sat, 31 Dec 2016 00:00:00 GMT",
            "revenue": 0,
            "runtime": 16,
            "title": "16.03",
            "vote_average": 8.0,
            "vote_count": 1
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "Documentary",
            "id": 414132,
            "keywords": "",
            "original_language": "es",
            "overview": "During the first year of a young girl's life the relationship between human beings and nature is shown over the course of time.",
            "popularity": 0.6,
            "poster_path": "",
            "production_companies": "",
            "recommendations": "nan",
            "release_date": "Fri, 01 Jan 2016 00:00:00 GMT",
            "revenue": 0,
            "runtime": 78,
            "title": "TEMPO",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "",
            "id": 855046,
            "keywords": "",
            "original_language": "pt",
            "overview": "While exploring the inside of a tree a little girl embarks on a mystical journey to the heart of the Tr\u00e1s-os-Montes region.",
            "popularity": 0.6,
            "poster_path": "/qpz9fzANtSQZ2DQwZId7qox8qLv.jpg",
            "production_companies": "",
            "recommendations": "nan",
            "release_date": "Tue, 20 Jul 2021 00:00:00 GMT",
            "revenue": 0,
            "runtime": 15,
            "title": "Moss",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "Animation-Adventure-Family-Fantasy",
            "id": 667589,
            "keywords": "",
            "original_language": "en",
            "overview": "In a small native American village a young girl Aiyanna is playing hide and seek with her brother Tawa until she encounters a furtive blue light at the edge of the surrounding mystical forest\u2026.",
            "popularity": 0.6,
            "poster_path": "/rO6CSTmYqMpH3VPR9kBfBS51eZ5.jpg",
            "production_companies": "Isart Digital",
            "recommendations": "nan",
            "release_date": "Wed, 12 Jul 2017 00:00:00 GMT",
            "revenue": 0,
            "runtime": 5,
            "title": "Wakan",
            "vote_average": 6.0,
            "vote_count": 1
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "Fantasy",
            "id": 825043,
            "keywords": "future-past-nature-present day",
            "original_language": "sv",
            "overview": "During a walk in nature a young hiker finds a notebook. Soon after curiosity gets the better of her she finds out that it is not just a notebook that crossed her path.",
            "popularity": 0.617,
            "poster_path": "/e3iS9GpiXqiWIBYKtZ7Dk6Sc8JM.jpg",
            "production_companies": "Runlevel Two Productions-Yellow Angle Film",
            "recommendations": "nan",
            "release_date": "Sat, 28 Nov 2020 00:00:00 GMT",
            "revenue": 0,
            "runtime": 7,
            "title": "Virvel",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "/x3kSXcPTASvkzs5wD0hhgejr57P.jpg",
            "budget": 0,
            "genres": "",
            "id": 366612,
            "keywords": "",
            "original_language": "ko",
            "overview": "When a young girl has her nervous romantic advances spurned because she cannot find the words to express her feelings she takes a dejected walk through a wooded area. Finding an abandoned guitar she begins a surreal journey of the imagination to glimpse the loving relationship she longs for and prove she is not the only one who finds words hard to say.",
            "popularity": 0.6,
            "poster_path": "/g7nWCnN909iekBXctpYrYOVUscj.jpg",
            "production_companies": "",
            "recommendations": "nan",
            "release_date": "Sat, 03 Nov 2012 00:00:00 GMT",
            "revenue": 0,
            "runtime": 25,
            "title": "Hard to Say",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "Drama-Horror",
            "id": 399859,
            "keywords": "",
            "original_language": "en",
            "overview": "Military sounds chatter and static. Crackling voices over the ether. On a wooded road two girls are driving lost amongst the endless forest. The road finally runs out. ..Road Closed. Strange noises surround them the ferns begin to move something is closing in... They are not alone in these woods.",
            "popularity": 0.6,
            "poster_path": "",
            "production_companies": "",
            "recommendations": "nan",
            "release_date": "Thu, 29 May 2014 00:00:00 GMT",
            "revenue": 0,
            "runtime": 7,
            "title": "Turn Around When Possible",
            "vote_average": 5.0,
            "vote_count": 2
        },
        {
            "backdrop_path": "/s9aY94TD49hSq9rNDh9TmAB6Xpg.jpg",
            "budget": 0,
            "genres": "Thriller-Horror-Animation",
            "id": 400464,
            "keywords": "winter-child-short film",
            "original_language": "xx",
            "overview": "Time ago a winter morning a little girl went out looking for firewood she went away from home and came across a blood trail... she followed it.",
            "popularity": 0.6,
            "poster_path": "/dwma0yBMt6jTYY4UOLkX9twx4DS.jpg",
            "production_companies": "Cesarlinga",
            "recommendations": "nan",
            "release_date": "Sun, 01 Jun 2014 00:00:00 GMT",
            "revenue": 0,
            "runtime": 3,
            "title": "Zepo",
            "vote_average": 8.0,
            "vote_count": 2
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "Fantasy",
            "id": 451342,
            "keywords": "",
            "original_language": "fr",
            "overview": "In a village located in the central French region of Sologne a young girl notes the negative effects of urbanization on her environment; then she imagines the appearance of the Amp\u00e9lop\u00e8de a strange creature living in the woods.",
            "popularity": 1.4,
            "poster_path": "/inMWphMJAiTAXq8yC6YTfJZErQf.jpg",
            "production_companies": "Nanou Film-Office de Radiodiffusion T\u00e9l\u00e9vision Fran\u00e7aise",
            "recommendations": "",
            "release_date": "Wed, 25 Sep 1974 00:00:00 GMT",
            "revenue": 0,
            "runtime": 85,
            "title": "L'Amp\u00e9lop\u00e8de",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "Thriller",
            "id": 724168,
            "keywords": "",
            "original_language": "ru",
            "overview": "A girl and a strange guy are looking for a phone lost in the woods.",
            "popularity": 0.6,
            "poster_path": "/bB07pVoUiPGyZ02qkWmoybshHaj.jpg",
            "production_companies": "",
            "recommendations": "nan",
            "release_date": "Mon, 30 Sep 2013 00:00:00 GMT",
            "revenue": 0,
            "runtime": 10,
            "title": "Lost in the Woods",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "/m68XBbNGZ7akr8Hw3SFiQfOIyYJ.jpg",
            "budget": 0,
            "genres": "Drama",
            "id": 823799,
            "keywords": "",
            "original_language": "en",
            "overview": "A teenager attempts to deal with her anger by stealing her dad's drum kit and isolating herself with it in the forest.",
            "popularity": 0.6,
            "poster_path": "/eU479ghNAVNJ12oFoRPOrBA1LkO.jpg",
            "production_companies": "",
            "recommendations": "nan",
            "release_date": null,
            "revenue": 0,
            "runtime": 7,
            "title": "Where are the Drums?",
            "vote_average": 0.0,
            "vote_count": 0
        },
        {
            "backdrop_path": "",
            "budget": 0,
            "genres": "Animation",
            "id": 709125,
            "keywords": "",
            "original_language": "es",
            "overview": "A girl finds a little hole that grabs her attention when she visits her farm so she tries to explore it and find out its secret. After a rainy day a plant grows out of the hole to change the life of the girl and make her happier.",
            "popularity": 0.6,
            "poster_path": "/eQ02GTUgIE9k5McIhhkMEMnM0pU.jpg",
            "production_companies": "",
            "recommendations": "nan",
            "release_date": "Fri, 02 Jun 2017 00:00:00 GMT",
            "revenue": 0,
            "runtime": 5,
            "title": "A Hole",
            "vote_average": 0.0,
            "vote_count": 0
        }
    ]
}